[project]
name = "cai"
version = "0.1.0"
description = "Use LLM to create git commits"
authors = [{ name = "Thorsten Foltz", email = "thorsten.foltz@live.com" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyyaml>=6.0,<6.1",
    "openai>=1.0",
]

[project.scripts]
git-cai = "cai.cli:main"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
