[project]
name = "gcai"
version = "0.1.0"
description = "Use AI to create git commits"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.98.0",
    "python-dotenv>=1.1.0",
    "pyyaml>=6.0.2",
]
